# Generated by Django 4.1.1 on 2022-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('students_name', models.CharField(default='', max_length=25)),
                ('roll_number', models.CharField(default='', max_length=8)),
                ('room_number', models.IntegerField(default=0, max_length=3)),
                ('department', models.CharField(default='', max_length=20)),
                ('wing_name', models.CharField(default='', max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
