# Generated by Django 4.1.1 on 2022-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_students_detail_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_detail',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
    ]
