# Generated by Django 4.1.1 on 2022-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_students_detail_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_detail',
            name='wing_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
