# Generated by Django 4.1.1 on 2022-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_students_detail_wing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/students'),
        ),
    ]
