# Generated by Django 4.1.1 on 2022-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_students_detail_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_detail',
            name='email_id',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='students_detail',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
