# Generated by Django 4.1.1 on 2022-09-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_students_detail_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_detail',
            name='School',
            field=models.CharField(default='', max_length=25),
        ),
    ]
