# Generated by Django 4.0.4 on 2022-09-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_students_detail_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_detail',
            name='profile_image',
        ),
    ]
