# Generated by Django 4.0.4 on 2022-09-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comittee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('roll_number', models.CharField(default='', max_length=8)),
                ('room_number', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=30)),
                ('year', models.IntegerField(default=2022, max_length=4)),
                ('email_id', models.EmailField(default='', max_length=30)),
                ('phone_number', models.IntegerField(default=0)),
                ('School', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='fees_detail',
        ),
    ]
